spring.application.name=call-the-match

## MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/callthematch?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=rootpassword

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# create an drop het beste voor dev
spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.hibernate.ddl-auto=none

# actief profiel, als productie verwijder je dit
spring.profiles.active=dev